name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Tests
        run: cargo test --release
  build-and-deploy:
    name: Rust github pages deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: GalAster/yew-github-pages@v0.1.0
        run: |
          cd projects/xo-web
          trunk build
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
